//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int pno { get; set; }
        public string pname { get; set; }
        public Nullable<int> age { get; set; }
    }
}
